env:
  - GO111MODULE=on
before:
  hooks:
    - go mod download
builds:
  - main: ./cmd/captain/
    binary: captain
    env:
      - CGO_ENABLED=0
archive:
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
dockers:
  - binaries: ["captain"]
    image_templates:
      - "barpilot/captain:latest"
      - "barpilot/captain:{{ .Tag }}"
      - "barpilot/captain:{{ .Major }}"
    dockerfile: Dockerfile.goreleaser
