project_name: captain

env:
  - GO111MODULE=on
before:
  hooks:
    - go mod download
builds:
  - main: ./cmd/captain/
    binary: captain
    env:
      - CGO_ENABLED=0
archive:
  format: binary
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"

snapcraft:
  publish: false
  summary: Software to create fast and easy drum rolls.
  description: |
    This is the best drum roll application out there.
    Install it and awe!
  grade: devel
  confinement: devmode
  apps:
    captain:
      plugs: ["home", "docker", "system-files"]
  plugs:
    system-files:
      write: ["/var/run/docker.sock"]
brew:
  github:
    owner: barpilot
    name: homebrew-tap
  folder: Formula
  homepage: https://barpilot.io
  description: "Software to create fast and easy drum rolls."
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
dockers:
  - binaries: ["captain"]
    image_templates:
      - "barpilot/captain:latest"
      - "barpilot/captain:{{ .Tag }}"
      - "barpilot/captain:{{ .Major }}"
    dockerfile: Dockerfile.goreleaser
