language: go

go: 
  - 1.12.x
env:
  - GO111MODULE=on
cache:
  directories:
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod

services:
  - docker

before_install:
  - go mod download

install: true

after_script: git diff --exit-code
